11월/Django/연습/pjt_1/app_1/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('index/', views.index),
]

11월/Django/연습/pjt_1/app_2/urls.py
from django.urls import path
from . import views

app_name = 'app_2'
urlpatterns = [
    path('', views.index, name='index'),
    path('app_2/create/', views.create, name='create'),
]

11월/Django/연습/pjt_1/board/urls.py
from django.urls import path
from . import views

# 메인페이지는 게시글의 목록 (R)
# 작성페이지는 따로 (C)
# 수정페이지도 따로 (U)

app_name = 'board'
urlpatterns = [
    path('', views.board, name='main'),
    path('write', views.write, name='write'),
    path('create', views.create, name='create'),
    path('delete/<int:pk>', views.delete, name='delete'),
]

11월/Django/연습/pjt_1/pjt_1/urls.py
from django.contrib import admin
from django.urls import path, include
# from app_1 import views as app_1_views
# from app_2 import views as app_2_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app_1/', include('app_1.urls')),
    path('', include('app_2.urls')),
    path('board/', include('board.urls')),
    path('posts/', include('posts.urls')),
]

11월/Django/연습/pjt_1/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
]

11월/Django/연습/pjt_1/app_1/models.py
from django.db import models

# Create your models here.

11월/Django/연습/pjt_1/app_2/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    content = models.TextField()
# 얘들을 DB로 만들려면 makemigrations으로 설계도만들고 migrate로 DB만듦...
# python manage.py makemigrations
# python manage.py migrate

11월/Django/연습/pjt_1/board/models.py
from django.db import models

# Create your models here.
class board1(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()

11월/Django/연습/pjt_1/posts/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    content = models.CharField(max_length = 80)
    completed = models.BooleanField(default=False)
    priority = models.IntegerField(default=3)
    created_at = models.DateField(auto_now_add=True)
    deadline = models.DateField(null=True)

11월/Django/연습/pjt_1/app_1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {
        
    }
    return render(request, 'app_1/index.html', context)

11월/Django/연습/pjt_1/app_2/views.py
from django.shortcuts import render
from .models import Article
# 현재폴더의 models에서 Article 가져오기 (DB 참고)

guestbook = []
# Create your views here.
def index(request):
    guestbook = Article.objects.all()
    # Select * FROM Articles
    context = {
        'guestbook' : guestbook
        # 'guestbook' : guestbook, 이것도 의미없어짐
        # DB에서 가져오기 하면 된다
    }
   
    return render(request, 'app_2/index.html', context)

def create(request):
    content = request.GET.get('content')
    Article.objects.create(content=content)
    context = {
        'content' : content,
        # 'guestbook' : guestbook.append(content), < 얘는 그냥 서버가 닫히면 리스트가 초기화 됨.
        # DB에 저장을 해야 영구적으로 남는다.
    }
    return render(request, 'app_2/create.html', context)

11월/Django/연습/pjt_1/board/views.py
from django.shortcuts import render, redirect
from .models import board1
# DB의 이름과 view.py 내부의 함수이름이 같아버리면 오류가 생긴다 (board가 중첩이 되버렸음)


# Create your views here.
def board(request):
    # 여기서는 모든 글 목록을 보여줘야함
    # 1. DB에서 모든 글 불러오기
    posting = board1.objects.all()
    # 2. 템플릿에 보내주기, context 이하가 템플릿에 보내주는거임.

    context = {
        'posting' : posting,
    }
    return render(request, 'board/board.html', context)

def write(request):
    return render(request, 'board/write.html')

def create(request):
    # 1. 파라미터로 날아온 데이터를 받아서
    title = request.GET.get('title')
    content = request.GET.get('content')
    # 2. DB에 저장
    board1.objects.create(title=title, content=content)
    # board를 불러오기위해 상단에 from .models(현재폴더의 models파일) 로 부터 DB를 import 해온다
    # board의 title 칼럼에 현재 함수에서 request.GET.get('title')을 해온 title을 할당시켜준것임

    context = {
        'title' : title,
        'content' : content,
    }
    return redirect('board:main')

def delete(request, pk):
    board1.objects.get(id=pk).delete()
    return redirect('board:main')

11월/Django/연습/pjt_1/posts/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'posts/index.html')

11월/Django/연습/pjt_1/app_1/templates/app_1/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  dd
</body>
</html>

11월/Django/연습/pjt_1/app_2/templates/app_2/create.html
{% extends 'base.html' %}

{% block content %}
  <p>글 작성: {{ content }}</p>
  <a href="{% url 'app_2:index' %}"> 돌아가기 </a>
{% endblock content %}

11월/Django/연습/pjt_1/app_2/templates/app_2/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>방명록</h1>
  <div>
    <h2>글 목록</h2>
    {% for i in guestbook %}
    <p>{{ i.content }}</p>
    {% endfor %}
  </div>
  <div>
    <h2>글작성</h2>
    <form action="{% url 'app_2:create' %}" method="GET">
      <input type="text" name="content">
      <input type="submit">
    </form>
  </div>
{% endblock content %}

11월/Django/연습/pjt_1/board/templates/board/board.html
{% extends 'base.html' %}

{% block content %}
  <h1>메인 페이지</h1>
  <ul>
    {% for i in posting %}
    <li>
      제목 : {{ i.title }} 내용 : {{ i.content }} <a href="">[수정]</a> <a href="/board/delete/{{ i.id }}">[삭제]</a>
    </li>
    
    {% endfor %}
  </ul>
  <a href="{% url 'board:write' %}">ㅁㄹ</a>
{% endblock content %}

11월/Django/연습/pjt_1/board/templates/board/create.html
{% extends 'base.html' %}

{% block content %}
  <p>등록되엇슴</p>
  <p>제목: {{ title }}</p>
  <p>내용: {{ content }}</p>
  <a href="{% url 'board:main' %}">목록으로</a>
  <!-- a태그에서  url 'board:html파일' 이걸 할때, board:board가 되면 에러가 난다.... 어플이름과 html파일이 동일하게 만들지 말자 -->
  <!-- 그리고 장고는 html파일 주석도 인식을 하니 코드를 막 적지 말자 -->
  <!-- board때문에 문제가 생긴게 아니고 여기서 참고하는건 urls.py에 붙어있는 name을 참고하는거라 그런거였음 -->
{% endblock content %}

11월/Django/연습/pjt_1/board/templates/board/write.html
{% extends 'base.html' %}

{% block content %}
  <h1>새 글 쓰기</h1>
  <form action="{% url 'board:create' %}">
    제목: <input type="text" name="title"><br>
    내용: <input type="text" name="content">
    <input type="submit">
    <!-- submit을 하면 create로 파라미터로 날아간 데이터를 db에 저장해줘야됨 -->
    <!-- request.GET.get('title'), request.GET.get('content') -->
  </form>
{% endblock content %}

11월/Django/연습/pjt_1/posts/templates/posts/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>index</h1>
  <form action="">
    <input type="text" name="index" maxlength="80">
    <input type="submit" value="할 일 추가">
  </form>
</body>
</html>