11월/Django/연습/moviereview/moviereview/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('review/', include('review.urls')),

]

11월/Django/연습/moviereview/review/urls.py
from django.urls import path
from . import views

app_name = 'review'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete', views.delete, name='delete'),
]

11월/Django/연습/moviereview/review/models.py
from django.db import models

# Create your models here.

class mo_re(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    updated_at = models.DateField(auto_now=True)
    created_at = models.DateField(auto_now_add=True)

11월/Django/연습/moviereview/review/views.py
from django.shortcuts import render, redirect
from .models import mo_re

def index(request):
    review = mo_re.objects.all()
    context = {
        'review' : review,
    }

    return render(request, 'review/index.html', context)

def detail(request, pk):
    article = mo_re.objects.get(pk=pk)
    context = {
        'article' : article,

    }
    return render(request, 'review/detail.html', context)

def new(request):
    return render(request, 'review/new.html')

def create(request):
    # new에서 title, content의 name을 가진 입력들을 가져온다
    title = request.GET.get('title')
    content = request.GET.get('content')
    # DB에 새로운 mo_re 저장하기
    mo_re.objects.create(
        title = title,
        content = content,
    )
    return redirect('review:index')

def delete(request, pk):
    article = mo_re.objects.get(pk=pk)
    article.delete()
    return redirect('review:index')

11월/Django/연습/moviereview/review/templates/review/create.html
{% extends 'base.html' %}

{% block content %}

{% endblock content %}

11월/Django/연습/moviereview/review/templates/review/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>글 내용</h1>
  <div>제목: {{ article.title }}</div>
  <div>내용: {{ article.content }}</div>

{% endblock content %}

11월/Django/연습/moviereview/review/templates/review/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>리뷰 사이트</h1>
  <a href="{% url 'review:new' %}"> 글 작성하기 </a>
  <hr>
  <div>
    {% for i in review %}
    <a href="{% url 'review:detail' i.pk %}">{{ i.title }}</a><br>
    <!-- 아래는 delete -->
    <form action="{% url 'review:delete' i.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="삭제">
    </form>
    <hr>
    {% endfor %}
  </div>
{% endblock content %}

11월/Django/연습/moviereview/review/templates/review/new.html
{% extends 'base.html' %}

{% block content %}
  <form action="{% url 'review:create' %}" method="GET">
    <label for="title">제목</label>
    <input type="text" id="title" name="title">

    <label for="content">내용</label>
    <input type="text" id="content" name="content"><br>
    <input type="submit">
  </form>

{% endblock content %}

11월/Django/연습/moviereview/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>