11월/Django/연습/todos/todolist/urls.py
from django.urls import path
from . import views

app_name = 'todolist'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('delete/<int:pk>', views.delete, name='delete'),
    path('create/', views.create, name='create'),
    path('edit/', views.edit, name='edit'),
]

11월/Django/연습/todos/todos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todolist/', include('todolist.urls')),
]

11월/Django/연습/todos/todolist/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    content = models.CharField(max_length=80)
    completed = models.BooleanField(default=False)
    priority = models.IntegerField(default=3)
    created_at = models.DateField(auto_now_add=True)
    deadline = models.DateField(null=True)

11월/Django/연습/todos/todolist/views.py
from django.shortcuts import render, redirect
from .models import Todo

# Create your views here.
def index(request):
    # 1.Todo 테이블의 내용물들을 다 읽어와서
    content = Todo.objects.all()
    # 2. 그것을 context에 넣은 뒤 html파일로 보내줌
    
    context = {
        'contents' : content
    }

    return render(request, 'todolist/index.html', context)

def add(request):
    content = request.GET.get('contents')
    # index.html의 input name이 contents니까 그걸 가져옴

    Todo.objects.create(content=content)
    # DB에 저장하기
    return redirect('todolist:index')
    # 얘를 redirect를 안하면 add/~~ 페이지로 넘어가서, 작업을 해놓은게 안보이는 페이지가 나옴
    # 리다이렉트로 원래페이지로 바로넘어가게 설정해주면 됨

def delete(request, pk):
    identity = Todo.objects.get(id=pk)
    identity.delete()
    return redirect('todolist:index')

def create(request):
    title = request.GET.get('title')
    content = request.GET.get('content')
    return render(request, 'todolist/create.html')

def edit(request):
    context = {
        'post' : post,
    }
    return render(request, 'todolist/edit.html', context)

11월/Django/연습/todos/todolist/templates/todolist/create.html
{% extends 'base.html' %}

{% block content %}
<h1>글 작성</h1>
<p>제목 : {{ title }}</p>
<p>내용 : {{ content }}</p>
{% endblock content %}

11월/Django/연습/todos/todolist/templates/todolist/edit.html
{% extends 'base.html' %}

{% block content %}
<h1>수정 페이지</h1>
  <form action="{% url 'todolist:create' %}">
    제목 : <input type="text" name="title"> <br>
    내용 : <input type="text" name="content">
    <input type="submit">
  </form>
{% endblock content %}

11월/Django/연습/todos/todolist/templates/todolist/index.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'todolist:add' %}">
  <input type="text" name="contents" maxlength="80">
  <input type="submit" value="할 일 추가">
</form>
<hr>

<ul>
  {% for i in contents %}
  <li>할일 : {{ i.content }} 완료여부 : {{ i.completed }} 
    <a href="{% url 'todolist:delete' i.pk %}">삭제</a> 
    <a href="{% url 'todolist:edit' i.pk %}">수정</a></li>
  {% endfor %}
</ul>
{% endblock content %}